run:
  timeout: 5m
  modules-download-mode: vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/DmitriyGoryntsev/huddle
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0